name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configurar y compilar el proyecto
        run: |
          mkdir build
          cd build
          cmake .. -DENABLE_TESTING=ON
          cmake --build .

      - name: Ejecutar pruebas unitarias
        run: |
          cd build
          ctest --output-on-failure
